# Generated by Django 2.2.4 on 2019-09-02 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailcapture', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestIpInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('country_code', models.CharField(blank=True, max_length=255, null=True)),
                ('country_name', models.CharField(blank=True, max_length=255, null=True)),
                ('dma_code', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.CharField(blank=True, max_length=255, null=True)),
                ('longitude', models.CharField(blank=True, max_length=255, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=255, null=True)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('time_zone', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
