# Generated by Django 2.2.4 on 2019-09-02 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emailcapture', '0002_requestipinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadcaptureemail',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='location', to='emailcapture.RequestIpInfo'),
            preserve_default=False,
        ),
    ]
